-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 01:06:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Endereco` ;

CREATE TABLE IF NOT EXISTS `Endereco` (
  `idEndereco` INT NOT NULL,
  `numero` INT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`));
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contato`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Contato` ;

CREATE TABLE IF NOT EXISTS `Contato` (
  `CPFCNPJ` VARCHAR(54) NOT NULL,
  `NomeRazao` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `dataNasc` DATETIME NOT NULL,
  `canalCaptacao` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`CPFCNPJ`),
  CONSTRAINT `fk_Contato_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

CREATE INDEX `fk_Contato_Endereco1_idx` ON `Contato` (`Endereco_idEndereco` ASC);


-- -----------------------------------------------------
-- Table `Negociacao`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Negociacao` ;

CREATE TABLE IF NOT EXISTS `Negociacao` (
  `idNegociacao` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  `dataAbertura` DATETIME NOT NULL,
  `dataEfetivacao` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` INT NULL,
  `descricao` VARCHAR(45) NULL,
  `anexo` VARCHAR(45) NULL,
  PRIMARY KEY (`idNegociacao`));
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerfilContato`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `PerfilContato` ;

CREATE TABLE IF NOT EXISTS `PerfilContato` (
  `idPerfilContato` INT NOT NULL,
  `ultimaAlteracao` VARCHAR(45) NOT NULL,
  `potencial` INT NOT NULL,
  `acoesFuturas` VARCHAR(45) NOT NULL,
  `padraoComportamento` VARCHAR(45) NOT NULL,
  `principalInteresse` VARCHAR(45) NOT NULL,
  `Contato_CPF_CNPJ` VARCHAR(54) NOT NULL,
  PRIMARY KEY (`idPerfilContato`),
  CONSTRAINT `fk_PerfilContato_Contato1`
    FOREIGN KEY (`Contato_CPF_CNPJ`)
    REFERENCES `Contato` (`CPFCNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

CREATE INDEX `fk_PerfilContato_Contato1_idx` ON `PerfilContato` (`Contato_CPF_CNPJ` ASC);


-- -----------------------------------------------------
-- Table `Relacionamento`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Relacionamento` ;

CREATE TABLE IF NOT EXISTS `Relacionamento` (
  `idRelacionamento` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  `dataReg` DATETIME NOT NULL,
  `descReg` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `Contato_CPFCNPJ` VARCHAR(54) NOT NULL,
  PRIMARY KEY (`idRelacionamento`),
  CONSTRAINT `fk_Relacionamento_Contato1`
    FOREIGN KEY (`Contato_CPFCNPJ`)
    REFERENCES `Contato` (`CPFCNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

CREATE INDEX `fk_Relacionamento_Contato1_idx` ON `Relacionamento` (`Contato_CPFCNPJ` ASC);


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_Usuario_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Endereco1_idx` ON `Usuario` (`Endereco_idEndereco` ASC);


-- -----------------------------------------------------
-- Table `Contato_has_Negociacao`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `Contato_has_Negociacao` ;

CREATE TABLE IF NOT EXISTS `Contato_has_Negociacao` (
  `Contato_CPFCNPJ` VARCHAR(54) NOT NULL,
  `Negociacao_idNegociacao` INT NOT NULL,
  PRIMARY KEY (`Contato_CPFCNPJ`, `Negociacao_idNegociacao`),
  CONSTRAINT `fk_Contato_has_Negociacao_Contato1`
    FOREIGN KEY (`Contato_CPFCNPJ`)
    REFERENCES `Contato` (`CPFCNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_has_Negociacao_Negociacao1`
    FOREIGN KEY (`Negociacao_idNegociacao`)
    REFERENCES `Negociacao` (`idNegociacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

CREATE INDEX `fk_Contato_has_Negociacao_Negociacao1_idx` ON `Contato_has_Negociacao` (`Negociacao_idNegociacao` ASC);

CREATE INDEX `fk_Contato_has_Negociacao_Contato1_idx` ON `Contato_has_Negociacao` (`Contato_CPFCNPJ` ASC);


--SET SQL_MODE=@OLD_SQL_MODE;
--SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
--SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
